#!/usr/bin/env node
// Regenerates content/off-the-clock/reading.md from:
//  1. the Obsidian vault's claude-recs tracker (currently reading)
//  2. the Goodreads "read" shelf RSS, items with a read-date only (recently finished)
// Run locally (needs the vault + network): npm run sync-reading

import { readFileSync, writeFileSync } from "node:fs"
import { homedir } from "node:os"
import { join } from "node:path"

const GOODREADS_USER = "50713490"
const GOODREADS_PROFILE = `https://www.goodreads.com/user/show/${GOODREADS_USER}`
const VAULT_IN_FLIGHT = join(
  homedir(),
  "Library/Mobile Documents/iCloud~md~obsidian/Documents/prh/2-Library/Books/claude-recs/in-flight.md",
)
const OUT = new URL("../content/off-the-clock/reading.md", import.meta.url).pathname
const MAX_FINISHED = 8

// --- currently reading, from the vault tracker -------------------------------
function currentlyReading() {
  const text = readFileSync(VAULT_IN_FLIGHT, "utf8")
  // slot entries live below the first horizontal rule; above it is a format example
  const body = text.split(/\n---\n/).slice(1).join("\n---\n")
  const books = []
  for (const m of body.matchAll(/^- \*\*(.+?)\*\* — (.+?) · started/gm)) {
    books.push({ title: m[1], author: m[2] })
  }
  return books
}

// --- recently finished, from the Goodreads read-shelf RSS --------------------
function cdata(block, tag) {
  const m = block.match(new RegExp(`<${tag}>\\s*(?:<!\\[CDATA\\[)?(.*?)(?:\\]\\]>)?\\s*</${tag}>`, "s"))
  return m ? m[1].trim() : ""
}

async function recentlyFinished() {
  const url = `https://www.goodreads.com/review/list_rss/${GOODREADS_USER}?shelf=read`
  const res = await fetch(url, { headers: { "User-Agent": "Mozilla/5.0" } })
  if (!res.ok) throw new Error(`Goodreads RSS: HTTP ${res.status}`)
  const xml = await res.text()
  const items = [...xml.matchAll(/<item>(.*?)<\/item>/gs)].map((m) => m[1])
  const books = items
    .map((it) => ({
      title: cdata(it, "title"),
      author: cdata(it, "author_name"),
      readAt: cdata(it, "user_read_at"),
    }))
    .filter((b) => b.readAt)
    .map((b) => ({ ...b, date: new Date(b.readAt) }))
    .filter((b) => !isNaN(b.date))
  // "recently" means the last 18 months
  const cutoff = new Date()
  cutoff.setMonth(cutoff.getMonth() - 18)
  books.sort((a, b) => b.date - a.date)
  return books.filter((b) => b.date >= cutoff).slice(0, MAX_FINISHED)
}

// --- page ---------------------------------------------------------------------
function fmt(d) {
  return d.toLocaleDateString("en-US", { month: "short", year: "numeric" })
}

const current = currentlyReading()
const finished = await recentlyFinished()

const lines = [
  "---",
  "title: Reading list",
  "---",
  "",
  "What's open on the desk right now, and what I've finished lately.",
  "",
  "## Currently reading",
  "",
  ...current.map((b) => `- **${b.title}** — ${b.author}`),
  "",
  "## Recently finished",
  "",
  ...finished.map((b) => `- **${b.title}** — ${b.author} · <small>${fmt(b.date)}</small>`),
  "",
  `The longer trail is on [Goodreads](${GOODREADS_PROFILE}).`,
  "",
  "<!-- Generated by scripts/sync-reading.mjs — edit there, then `npm run sync-reading`. -->",
  "",
]

writeFileSync(OUT, lines.join("\n"))
console.log(
  `reading.md updated: ${current.length} currently reading, ${finished.length} recently finished`,
)
